### ISSUE TITLE
Ошибки на сайте

### ISSUE THREAD

**Issue by yarkovaleksei** [vue-faq/vue-faq.github.io#12]
Не отображаются иконки
http://joxi.ru/82Q0GNgH1eDpWm

Не работает переключение страниц
http://joxi.ru/Q2Kl8ByH9DbqkA

**Comment by Amareis** [comment]
Пофикшено

**Comment by yarkovaleksei** [comment]
Нет, не пофикшено
http://joxi.ru/Q2Kl8ByH9D9eYA

**Comment by xrei** [comment]
Sorry but you have to install fonts on your system yourself, otherwise it wouldn't be displayed
